### ISSUE TITLE
how to configure sshrun?

### ISSUE THREAD

**Issue by Neimd** [NetEase/pomelo#693]
i set up 3 machines for my game server distributed deployment.
same user name, absolute path, same code, same ssh config file. 
the ssh config file content is as follow :
Host *
HashKnownHosts no
CheckHostIP no
StrictHostKeyChecking no

and modify '../config/server.json', '../config/master.json'. files content is as follow :
// master.json
..
"production" : {
    "id" : "master-server-1",
    "host" : "master147.test.com",
    "port" : 3005
  }
..

// servers.json
"production" : {
    "gate" : [
      {
        "id" : "gate-server-1",
        "host" : "front185.test.com",
        "clientPort" : 3014,
        "frontend" : true
      }
    ],

```
"connector" : [
  {
    "id" : "connector-server-1",
    "host" : "front185.test.com",
    "port" : 3150,
    "clientPort" : 3010,
    "frontend" : true
  }
],

"chat" : [
  {
    "id" : "chat-server-1",
    "host" : "backend149.test.com",
    "port" : 6050
  }
]
```

..
}

above steps are completed. i use 'pomelo start -e 'production' ' command in master machine.

then, i got the following log message :
.
.
.
Host key verification failed.
Host key verification failed.
.
child process exit with error, error code: 255, executed command: ssh
.
.

how can i fix it?? please help me.

**Comment by wuxian** [comment]
sorry, my english is very poor
1.on the dest machine you need have the same user with the key
2.copy your public and private key to your home directory($HOME/.ssh)
3.rename to  id_rsa (private key) ,  id_rsa.pub (public key) and chmod 644
4.run command  ssh xxx.xx.xxx.xx(dest host), if you success connected to dest host, pomelo can too，为otherwise, you have to find your network administrator

**Comment by Neimd** [comment]
sorry, my english is very poor.

you save my time. thanks~
