### ISSUE TITLE
Is project discontinued? 该项目被放弃？

### ISSUE THREAD

**Issue by jesst3r** [NetEase/pomelo#877]
Greetings, pomelo is awesome, but there is no updates for a long time... Master branch build fails.  Is project discontinued by the founder?

pomelo, 非常有趣的项目，但没有更新，用户支持不进行......该项目被遗弃？

**Comment by magisters-org** [comment]
I have the same question to :).

**Comment by Foxhunt** [comment]
Same here, did 2.0 move some where else?

**Comment by andybn** [comment]
Me too. Same question.

**Comment by jesst3r** [comment]
more than a month, have passed, and no answer

**Comment by markchou** [comment]
我也想知道，太可惜了

**Comment by jesst3r** [comment]
我认为，支持将不会是...

**Comment by Illyrix** [comment]
This project may be given up....I guess...Because this is a project created for a company (NetEase) 4 years ago. With workers leaving this company, nobody wants to continue to work for it...And I don't know whether NetEase uses this project, may not?

估计没人了吧....4年前的项目,开发者离开网易就没人维护了....再说网易他自己用这个(不怎么维护的)框架么...

**Comment by fantasyni** [comment]
继续维护的

**Comment by kaktus42** [comment]
and in english?

**Comment by magisters-org** [comment]
@kaktus42 project alive

**Comment by fantasyni** [comment]
@kaktus42 yeah alive
